### PR TITLE
fix(client/server): Radio Object Creation

### LINKED ISSUE #42: When Player Use Radio Got Failed to spawn radioprop
### Summary

[    script:qbx_radio] SCRIPT ERROR: @qbx_radio/server/main.lua:47: Failed to spawn radioprop (waited 2017.0ms)

### Reproduction

When Player Useing Radio In game In Server Side  I Got This Error
`12:51:03 PM [    script:qbx_radio] SCRIPT ERROR: @qbx_radio/server/main.lua:47: Failed to spawn radioprop (waited 2017.0ms)
12:51:03 PM [    script:qbx_radio] > callbackResponse (@ox_lib/imports/callback/server.lua:83)
12:51:03 PM [    script:qbx_radio] > handler (@ox_lib/imports/callback/server.lua:100)
12:51:03 PM [    script:qbx_radio] 
12:51:44 PM [    c-scripting-core] script error in native 000000006e31e993: Argument at index 0 was null.`

### Expected behavior

Use Radio

### Actual behavior

Got This Error
`12:51:03 PM [    script:qbx_radio] SCRIPT ERROR: @qbx_radio/server/main.lua:47: Failed to spawn radioprop (waited 2017.0ms)
12:51:03 PM [    script:qbx_radio] > callbackResponse (@ox_lib/imports/callback/server.lua:83)
12:51:03 PM [    script:qbx_radio] > handler (@ox_lib/imports/callback/server.lua:100)
12:51:03 PM [    script:qbx_radio] 
12:51:44 PM [    c-scripting-core] script error in native 000000006e31e993: Argument at index 0 was null.
`

### Additional context

_No response_

### Current Version

Last Version Of github

### Custom Resources

no

### PR DESCRIPTION
**Pull request by ihyajb**
## Description

Now uses locally spawned client objects synced with state bags. Instead of fully server sided objects

Closes #42
Supersedes #43 

Tested with CL2 and all fine also 
Screenshot 2025-03-06 074409

## Checklist

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My pull request fits the contribution guidelines & code conventions.

### CODE REVIEW

File: server/main.lua [hunk 1]
```diff
@@ -24,57 +22,7 @@ for channel, jobs in pairs(restrictedChannels) do
...
-        deleteProp(i)
-    end
-end)
-
-RegisterNetEvent('qbx_radio:server:deleteProp', function()
+RegisterNetEvent('qbx_radio:server:setHoldingRadio', function(bool)
     local src = source
-
-    deleteProp(src)
+    Player(src).state.isHoldingRadio = bool
```
Comment (Ehbw) [inline server/main.lua:28]: It may be worth making sure that only a bool can be passed to this. As otherwise a client could sent a bunch of useless data to be attached to them

Comment (ihyajb) [reply server/main.lua:28]: Good Idea

**Review by Ehbw — APPROVED** [review]

**Review by FjamZoo — CHANGES_REQUESTED** [review]
This is close, but we also need a way to handle whenever a player leaves the other player scope, the way to handle this is 1 either loop or use the onPlayerDrop client event refer to Renewed-Weaponscarry here to see how I've done it:

https://github.com/Renewed-Scripts/Renewed-Weaponscarry/blob/main/modules/carry.lua#L16

**Comment by ihyajb** [comment]
Should be good now, renamed the `netId` var in the handler to be `serverId` to keep it more consistent also.

File: client/main.lua [hunk 2]
```diff
@@ -85,35 +85,49 @@ local function toggleRadio(toggle)
...
+        AttachEntityToEntity(Radios[serverId], ped, GetPedBoneIndex(ped, 28422), -0.01, 0.0, 0.0, 0.0, 0.0, 0.0, true, true, false, true, 1, true)
+        SetModelAsNoLongerNeeded(model)
+    end
+end)
+
+RegisterNetEvent('onPlayerDropped', function(serverId)
+    if not Radios[serverId] then return end
+    SetEntityAsMissionEntity(Radios[serverId], true, true)
+    DeleteEntity(Radios[serverId])
+    Radios[serverId] = nil
```
Comment (FjamZoo) [inline client/main.lua]: Looks good, the last little bit would probably just make this into a function so we adhere to the DRY principle.

Other than that this PR is good to go

Comment (ihyajb) [reply client/main.lua]: will do, also forgot to add the resource stop / restart check so will add that back also

**Comment by ihyajb** [comment]
- Added a `waitFor` to make sure the ped is valid
- Removed no longer needed locales
- Moved the cleanup to a function
- Added cleanup for resource stops / restarts

**Review by FjamZoo — APPROVED** [review]
Beutiful thanks AJ, merge whenever :)
